### ISSUE TITLE
General 

### ISSUE THREAD

**Issue by banillie** [banillie/project_tracker#1]
@yulqen I've had a good time putting together this code so far. The try django youtube tutorial was really useful. Got a couple of questions which I would appreciate your thoughts on, if you have a mo or two to consider:
- Do you have a preference of function or class based views in Django? I'm really wondering what a class based view will give you that a function won't. 
- I got a warning about the Django secret key in my project and have hived it off into a 'secret' file which I've reference in gitignore. Is this the proper thing to do? 
Cheers, Will.

**Comment by yulqen** [comment]
Looks good!  Glad you're making progress. Code looks good.

1. I would definitely stick to function-based views to start with. They are much easier to understand in terms of logic when you first get going: the func receives a request object and you do something with it and return as response. Class-based views are very handy once you're comfortable but they're a real pain to debug. Because they can be so terse (only one line in some cases), all the actual machinery is handled elsewhere inside the framework and the path can be very deep. Start with function-based - definately.

2. Keep the secret key out of your repo - definitely. Just don't check it in.  If you're doing that, you're doing it right.

Let me know if there's anything else.

**Comment by banillie** [comment]
@yulqen cheers. Will def stick to functions for now. I'll let you know if I've got any other issues - I've got a few already to look at next week, which I might need to bother you with. 
If you have sometime towards end of  next week to discuss the project - the db design, urls and http templates - that would be great.

**Comment by yulqen** [comment]
Absolutely no bother.

**Comment by banillie** [comment]
would you have any time Thursday or Friday?

**Comment by banillie** [comment]
Making a list of general queries:
- How do you debug?

**Comment by yulqen** [comment]
@yulqen Did I answer this??

**Comment by banillie** [comment]
Yes. We covered it on Friday. Cheers.
