### ISSUE TITLE
Working with static files

### ISSUE THREAD

**Issue by banillie** [banillie/project_tracker#18]
Need a better understanding of how django is handling static files both in development and production. 

- Static files are now being loaded to DO and not locally. Does this mean I need to run collect static every time? When developing css? 
- The code's folder structure for static files is different to DO. 
- When I run collect static should dirs/files be places into the staticfiles dir.

**Comment by banillie** [comment]
@yulqen could use your input on this one. I'm pretty stumped. 

I want to be able to load the static files I'm working with in development in the local project files as well as / or separate to the files I've loaded (via collect static) onto the Digital Ocean Spaces platform. At the moment all static files are being loaded from the DO space and I can't get the hmtl stylesheet tag to point to the local css file. 

Any help you can provide would be greatly appreciated!

**Comment by yulqen** [comment]
@banillie - As far as I recall, `collectstatic` simply copies all the static files out of each app in your project and puts them in a single place that your web server can use to access them for the whole site. You shouldn't need this in your development environment because you're running the Django development server which knows to look in each app's static files directory - this would be a pain to do with a production server.

Points to remember which might be useful - there are basically two main components in production: a web server (such as Nginx or Apache) which accepts requests from the internet and hands them off to the application server, which runs your Django code - this is often gunicorn or uwsgi or something similar. The application server handles all the Django logic - views, templates, etc, whilst the web server - as well as passing requests to the application server - will separately serve the static files.  The role of the web server handing off requests is often referred to as "reverse proxy" - in case you see that referenced.

Don't know anything about the Digital Ocean Spaces platform unfortunately, nor what exactly you're trying to do here. Do you not have any static files available to your in prod? Are you trying to do a `collectstatic` on the DO platform?

**Comment by banillie** [comment]
@yulqen Any chance you could have a convo about this sometime this week? I think I'm missing something obvious. 

Even in development / on local server when I inspect where files are being loaded from it's the DO spaces web page.

**Comment by yulqen** [comment]
Happy to discuss.

https://docs.djangoproject.com/en/3.2/howto/static-files/

**Comment by banillie** [comment]
I had a look at that guidance but will go through it again. 

Could you do sometime tomorrow/Friday pm for a chat? 

Cheers.

**Comment by yulqen** [comment]
Let's have a look on Friday. In the meantime, if you're serving static files from Digital Ocean in your development environment, something is wrong. You've probably done a `collectstatic` locally and somehow ended up with absolute URLs, pointing to the DO server.  Try to start again with the static files - follow the guidance above carefully and make sure your css files are in the correct place in your development environment (inside `static` directories inside each app) and get it working there. I don't know Digital Ocean spaces - it might be too complicated for me to be honest - I'm used to doing it manually! But lets see Friday.

**Comment by banillie** [comment]
'You've probably done a collectstatic locally and somehow ended up with absolute URLs, pointing to the DO server.'

Yes I think that's what you've done. 

I can't see where my static files are locally. 

Cool. Will have another look at this before Friday.

**Comment by yulqen** [comment]
@banillie See how you get on. I remember during my time with Django that dealing with static files was a total pain in the arse, to be honest.

**Comment by banillie** [comment]
@yulqen sorted! For now anyway! The tutorial I was using for handling static files set up a content delivery network directory which has a load of configurations for the production environment. One of the configurations was a default setting for static file storage, which points to the DO space. If I turn off the cdn config then it reverts back to collecting the static files from the local static file!!  line 175 in project_tracker.settings. 

I went around the houses of this one, but it has been useful for me to better understand how static loads are being loaded and managed. Cheers.

**Comment by yulqen** [comment]
@banillie - it's all a learning experience! Big benefits it keeping it as simple as possible much of the time. CDNs, managed hosting hosting, etc - all obscure what's really going on sometimes. We have enough complexity to deal with just creating the basic app sometimes!
